<?php
// This line is so VIM recognizes this as a PHP file:
// vim:ft=php:shiftwidth=3:tabstop=3:

/* 
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

// views: hook_views_api()
function views_spin_carousel_views_api() {
   return array( 'api' => 3.0 );
}

// views: hook_views_plugins()
function views_spin_carousel_views_plugins() {
   return array(
      'style' => array(
         'spin_carousel' => array(
            'title' => t( '3D Spinning Carousel' ),
            'help' => t( 'Displays a 3D spinning carousel with flipping '.
               'items on browsers that support it.' ),
            'handler' => 'views_plugin_style_spin_carousel',
            'theme' => 'views_spin_carousel',
            'uses fields' => true,
            'uses options' => true,
            'uses grouping' => false,
            'type' => 'normal',
            'even empty' => true,
         ),
      ),
   );
}

