<?php
// This line is so VIM recognizes this as a PHP file:
// vim:ft=php:shiftwidth=3:tabstop=3:

// views: hook_views_api()
function views_spin_carousel_views_api() {
   return array( 'api' => 3.0 );
}

// views: hook_views_plugins()
function views_spin_carousel_views_plugins() {
   return array(
      'style' => array(
         'spin_carousel' => array(
            'title' => t( '3D Spinning Carousel' ),
            'help' => t( 'Displays a 3D spinning carousel with flipping '.
               'items on browsers that support it.' ),
            'handler' => 'views_plugin_style_spin_carousel',
            'theme' => 'views_spin_carousel',
            'uses fields' => true,
            'uses options' => true,
            'uses grouping' => false,
            'type' => 'normal',
            'even empty' => true,
         ),
      ),
   );
}

